[build]
publish = "site/public"
command = "hugo -s site"

[context.production.environment]
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "hugo -s site -b $DEPLOY_PRIME_URL"


[context.branch-deploy]
command = "hugo -s site -b $DEPLOY_PRIME_URL"

